module.exports = {
  name: "DnD",
  logo: "icones/logomonde.jpg",
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: "Dague",
      logo: "./src/icones/Dague.jpg",
      cout: 1,
      croissance: 1.02,
      revenu: 100,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      palliers: [
        {
          name: "Fer",
          logo: "./src/icones/Dague.jpg",
          seuil: 20,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "./src/icones/Dague.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
      ],
    },

    
    {
      id: 2,
      name: "Epée",
      logo: "icones/deuxiemeproduit.jpg",
      cout: 5,
      croissance: 1.02,
      revenu: 250,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Fer",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 125,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },

      ]
    },
    {
      id: 3,
      name: "Hache",
      logo: "icones/deuxiemeproduit.jpg",
      cout: 20,
      croissance: 1.05,
      revenu: 500,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Fer",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },

      ]
    },
    {
      id: 4,
      name: "Arc",
      logo: "icones/deuxiemeproduit.jpg",
      cout: 7,
      croissance: 1.07,
      revenu: 25,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Fer",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
      ]
    },
    {
      id: 5,
      name: "Espadon",
      logo: "icones/deuxiemeproduit.jpg",
      cout: 10,
      croissance: 1.07,
      revenu: 70,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Fer",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },

      ]
    },
    {
      id: 6,
      name: "Arbalète",
      logo: "icones/deuxiemeproduit.jpg",
      cout: 5,
      croissance: 1.07,
      revenu: 50,
      vitesse: 500,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: "Fer",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },
        {
          name: "Acier",
          logo: "icones/deuxiemepalier.jpg",
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: "vitesse",
          unlocked: false,
        },

      ]
    },
  ],
  allunlocks: [
    {
      name: "Nom du premier unlock général",
      logo: "icones/premierunlock.jpg",
      seuil: 30,
      idcible: 0,
      ratio: 2,
      typeratio: "gain",
      unlocked: false,
    },
  ],
  upgrades: [
    {
      name: "Nom du premier upgrade",
      logo: "icones/premierupgrade.jpg",
      seuil: 1e3,
      idcible: 1,
      ratio: 3,
      typeratio: "gain",
      unlocked: false,
    },
  ],
  angelupgrades: [
    {
      name: "Sacrifice des âmes",
      logo: "icones/angel.png",
      seuil: 10,
      idcible: 0,
      ratio: 3,
      typeratio: "gain",
      unlocked: false,
    },
  ],

  managers: [
    {
      name: "Wangari Maathai",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 1,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    },
    {
      name: "Lae'zel de Kli'ir",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 2,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    },
    {
      name: "Karlach Cliffgate",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 3,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    },
    {
      name: "Astarion Ancunin",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 4,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    },
    {
      name: "Gale d'Eauprofonde",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 5,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    },
    {
      name: "Shadowheart",
      logo: "icones/WangariMaathai.jpg",
      seuil: 10,
      idcible: 6,
      ratio: 0,
      typeratio: "gain",
      unlocked: false,
    }
  ],
};
